### ISSUE TITLE
Android版onnxruntimeのビルドをする？

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/onnxruntime-builder#17]
## 内容

公式のAndroid版onnxruntimeは自動publishされておらず、メンテナンスが不安定な予感がしました。

- https://github.com/VOICEVOX/onnxruntime-rs/pull/19#issuecomment-1501773352

このリポジトリでAndroid版もビルドしておくと安心かもしれないので、メモ程度にissueを作成しました。

### Pros 良くなる点

安定する

### Cons 悪くなる点

ビルドしないといけない

### 実現方法

公式では確かandroid用のパッケージをビルドしていました、我々的には動的ライブラリだけがあれば良いと思います。

**Comment by qryxip** [comment]
#26 からlinkし忘れていました。
