### ISSUE TITLE
iOS向けXCFrameworkを追加する

### ISSUE THREAD

**Issue by HyodaKazuaki** [VOICEVOX/onnxruntime-builder#18]
## 内容

iOS向けにビルドされたdylibをまとめ、シミュレータや実機上でも利用可能なXCFrameworkを提供したいと思います。

### Pros 良くなる点

環境ごとに動的ライブラリを切り替える必要がなくなる

### Cons 悪くなる点

リリースに時間がかかるようになる

### 実現方法

1. 各ターゲット向けにonnxruntimeをビルドする
2. `lipo`を使ってシミュレータ向けターゲットを1つのFat binaryにする
3. `xcodebuild`を使ってXCFrameworkを作る

## その他

このIssueで提案する機能は、元々 https://github.com/VOICEVOX/voicevox_core/issues/477 で提案され、 https://github.com/VOICEVOX/voicevox_core/pull/485 で追加予定だったXCFrameworkの作成ジョブを移植したものになる予定です。

**Comment by Hiroshiba** [comment]
良いと思います！！

**Comment by Hiroshiba** [comment]
お久しぶりです！

ちょっとビルドオプション眺めてたんですが、`--build_apple_framework`というのがあることに気づきました！
https://github.com/microsoft/onnxruntime/blob/b9f3a5d5b62d12fb3d90b3e98bf7d05aa8a560d6/tools/ci_build/build.py#L302-L304

確か今は各々ビルドした後に色々くっつけてxcframeworkを作っていますが、このオプションを指定すれば良い感じになったりするかも？
issue作ってみたので、もしご興味あればコメントいただけると･･･！

- https://github.com/VOICEVOX/onnxruntime-builder/issues/49
