### ISSUE TITLE
macOSのarm64ビルドが正しくできない

### ISSUE THREAD

**Issue by stakemura** [VOICEVOX/onnxruntime-builder#29]
## 不具合の内容

macOSのarm64ビルドが正しくできない

### 現象・ログ

#28  を参照ください 

## OSの種類/ディストリ/バージョン

- [ ] Windows
- [x] macOS
- [ ] Linux

**Comment by Hiroshiba** [comment]
- https://github.com/VOICEVOX/onnxruntime-builder/pull/28

にて解決。
（修正ありがとうございます！！！）
