### ISSUE TITLE
本レポジトリ派生版の業務利用についてお伺い

### ISSUE THREAD

**Issue by stakemura** [VOICEVOX/onnxruntime-builder#34]
stakemuraです。先日はPRなど反映していただきありがとうございました。

 @Hiroshiba san への質問になります。
実はONNX Runtimeをカスタムビルド版を業務で利用する予定がございまして、現在試験的に下記レポジトリのような形でビルドしております。
https://github.com/stakemura/onnxruntime-minimal-builder
 
ご覧の通り、iOS版については公式のxcframeworkビルドスクリプトを使うためほぼ別物、その他プラットフォームはベースは本レポジトリのスクリプトを一部踏襲しているもののカスタムビルドになるため、出力バイナリは大きく異なっております。

お伺いしたいのは、ライセンスに関する取り扱いです。上記レポジトリを運用するにあたって、どのような形でライセンスを記載するのが望ましいでしょうか？「LICENSEの `Copyright (c) 2021 VOICEVOX` はそのままにしてほしい」「READMEで引用元として本レポジトリが示されていればOK」など温度感をお聞かせいただければ幸いです。

なお、上記レポジトリは最終的に下記レポジトリのように、社内OSSとしてownerをtransferする予定がございます。
https://github.com/DeNA/tflite-runtime-builder

お返事お待ちしております。

**Comment by qryxip** [comment]
横から失礼します。

このリポジトリは @Hiroshiba さん、今話している私(@qryxip)、stakemuraさんご自身を含めた9人で作った著作物であり、CLAを結んでいない以上は残りの6人と連絡が取れないのなら安全側に倒した方がよいのではないかと私は考えています。おそらくその点はVOICEVOXにとっても御社にとっても共通するのではないかと思います。

私が考える安全側として、とりあえず思い付くのは次の2つです。

1. リポジトリを作り直してGitHub上でもVOICEVOX/onnxruntime-builderのフォークとし、VOICEVOXのコミットもLICENSEファイルも残した上で、その上からDeNAとしてのコミットを重ねる
2. VOICEVOX側のスクリプト由来の部分すべてに、YAMLのコメントでMIT Licenseの表記を入れる。またLICENSEファイルも純粋なMITとせず、VOICEVOX/onnxruntime-builder由来のMIT LicenseとDeNAとしてのMIT Licenseが含まれていることを明記する
    - できるならVOICEVOX由来の部分はコミットを分け、(co-)authorとして必要な名前(最大8人)を入れる

ただ9人のうちここにいない6人と全員連絡が取れるなら最悪別ライセンスの締結ができるので、そのときはもしかしたらREADMEでの紹介に落ち着けられるかもしれません。

**Comment by Hiroshiba** [comment]
@qryxip さん、ありがとうございます！！
そういえば、なぜLICENSEのコピーライトにコントリビューター全員を書く必要が無いのかとか、各コードにライセンス表記しなくても良いのかとかわからなくてちょっと調べてました。
Gitとかで追えるからOKっしょ、みたいな感じなんですね。

---

@stakemura 僕の意見を書きます 🙏 

個人的には、MITライセンスの許す範囲であれば大丈夫です。
ライセンスの守り方は @stakemura sanやDeNAさんの責任と判断におまかせします。

･･･とさっぱり書きたかったのですが、やっぱりVOICEVOXの名前があると嬉しいですね！！！！！！！
なのでDeNAさん的にそれでOKなのであれば、READMEで引用があると嬉しいです！！！

**Comment by stakemura** [comment]
@qryxip @Hiroshiba 
早速のレスポンスありがとうございます！
すべてではないのですが、お二方の意見を取り入れ、VOICEVOX/onnxruntime-builderをフォークし、VOICEVOXのコミット履歴も残した上でLICENSEファイルに追記したレポジトリを用意しました。前述のレポジトリとはURLが微妙に異なるため、ご注意ください。

https://github.com/stakemura/onnxruntime-builder/

LICENSEは以下のような記載になっております。

```
Copyright (c) 2021 VOICEVOX
Copyright (c) 2021 other contributors
Copyright (c) 2024 DeNA
```

お手数おかけして申し訳ないのですが、上記レポジトリを改めてご確認いただきコメント頂けると幸いです

**Comment by Hiroshiba** [comment]
@stakemura ライセンス的にその記載で大丈夫という権限は僕にないのですが、少なくともVOICEVOXのお気持ち的には問題ないです！！

**Comment by qryxip** [comment]
@stakemura 私としてもまた考えたのですが、コントリビュータの意思とは関係なくやはり御社の判断でMITライセンスを遵守して頂く形の方がよいと思いました。

私が提示した方法ですが、考慮が抜けている部分があるかもしれません。勝手ながらアドバイスさせていただくと、御社のなかで相談できる先があるのなら相談するのがよいかもしれないと思いました。

**Comment by stakemura** [comment]
@Hiroshiba @qryxip
レスポンス感謝です。
まず、社内OSSにあたり、もともとMIT Licenseを遵守することが会社の方針として求められているので問題ございません（[tflite-runtime-builder](https://github.com/DeNA/tflite-runtime-builder)も同じ）。一方LICENSEの記載については、これが正しいのか当方では判断がつかないのですが、この後リーガルチェックを通すことになっておりますので、もしなにかあればFeedback致します。
このたびは本当にありがとうございました。

**Comment by stakemura** [comment]
@Hiroshiba @qryxip
こちらご連絡が遅れましたが、LICENSEはあれから変更なく、下記URLにて運用中です。
https://github.com/DeNA/onnxruntime-builder

これまでのご対応、感謝致します。本commentをもって、Closeさせて頂きます。
