### ISSUE TITLE
`armv7l`と`aarch64`が`ubuntu-20.04`上でビルドできていない

### ISSUE THREAD

**Issue by qryxip** [VOICEVOX/onnxruntime-builder#9]
<https://github.com/VOICEVOX/onnxruntime-builder/pull/8#issuecomment-1475076711>

この件についてまだあまり調べていませんが、今CIが落ちている状態なのでissueを立てたいと思います。

**Comment by Hiroshiba** [comment]
おっとなるほどです！　issue作成ありがとうございます！！

**Comment by aoirint** [comment]
原因の調査だけしてみました。

Ubuntu 20.04から（正確には19.04から）、`/lib`が`/usr/lib`へのシンボリックリンクになった（UsrMerge）ことで、CIで想定していないディレクトリ構成になったことが原因かもです。

- <https://wiki.debian.org/UsrMerge>
- <https://gihyo.jp/admin/clip/01/ubuntu-topics/202011/06>

具体的には、以下の処理が怪しいです。
18.04では、`/lib/arm-linux-gnueabihf`は存在しませんが、`/usr/lib/arm-linux-gnueabihf`は存在していました。
20.04では、（UsrMergeで）`/lib/arm-linux-gnueabihf`が存在するようになったので、96行目で作成されるシンボリックリンクは、想定された`/lib/arm-linux-gnueabihf`ではなく、`/lib/arm-linux-gnueabihf/lib`になっていそうです。
97行目では`/lib/arm-linux-gnueabihf`直下を検索するため、`/lib/arm-linux-gnueabihf/lib`以下は検索されず、`ld-*.so`が見つかからず、エラーメッセージ（`/lib/ld-linux-armhf.so.3: No such file or directory`）にある`/lib/ld-linux-armhf.so.3`が作成されていないのかなと思います。

https://github.com/VOICEVOX/onnxruntime-builder/blob/6a9d30829f40954714a8830f415c19aa0cb46336/.github/workflows/build.yml#L94-L98

- <https://qiita.com/tetsu_koba/items/9bdcb59f912efbff3128#%E3%83%80%E3%82%A4%E3%83%8A%E3%83%9F%E3%83%83%E3%82%AF%E3%83%AA%E3%83%B3%E3%82%AF%E3%81%95%E3%82%8C%E3%81%9Farm%E3%81%AE%E5%AE%9F%E8%A1%8C%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%82%E3%81%9D%E3%81%AE%E3%81%BE%E3%81%BE%E5%AE%9F%E8%A1%8C%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B>

97行目の`/lib/ld-linux-armhf.so.3`はシンボリックリンクのターゲットにするパスを変更すれば作成できそうですが、
96行目の`/lib/arm-linux-gnueabihf`の直下にその他のARM向けの`*.so`（`/usr/arm-linux-gnueabihf/lib`にあるもの）を配置する処理が必要かどうかはよくわからないです。

（94行目のコメントによるとコンパイル中にExec Format Errorというエラーが起きないようにするための変更らしいですが、泥臭い処理なので他の方法で代替できればした方がいいとは思います）

環境再現用のコマンド

```shell
# Ubuntu 18.04
docker run --rm -it ubuntu:18.04 bash
apt update
apt install gcc-8-arm-linux-gnueabihf g++-8-arm-linux-gnueabihf
```

```shell
# Ubuntu 20.04
docker run --rm -it ubuntu:20.04 bash
apt update
apt install gcc-8-arm-linux-gnueabihf g++-8-arm-linux-gnueabihf
```

**Comment by Hiroshiba** [comment]
なーーーるほどです！！

armhf環境でどうビルドするのが筋が良いのかよくわかりませんね･･･。
onnxruntimeのarm64ビルドあたりをどうしているか探ればヒントが得られるかもですが、普通にarm64マシンでビルドすることを想定されていたりしそうですし 😇 

あるいは、ディレクトリ先を変更しちゃえばとりあえずビルドできたりしそうでしょうか。
いったん泥臭くてもいいのでワークアラウンドで解決でも良いのかもとかちょっと思いました。
